### ISSUE TITLE
No Exit on Login Screen

### ISSUE THREAD

**Issue by changchup** [auth0/react-native-lock-ios#16]
I notice there is a cancel button in the top right hand corner of the images in the README but when I followed instructions it does not appear.  Can you tell me how to add it?
![screen shot 2016-03-24 at 5 33 52 pm](https://cloud.githubusercontent.com/assets/7632487/14087658/755e8d34-f501-11e5-80e5-31081c25e971.png)

**Comment by lbalmaceda** [comment]
Hi there,
Try to set `closable` to true on the Lock options.

Ref: https://github.com/auth0/react-native-lock-ios#showoptions-callback

**Comment by changchup** [comment]
thank you
