### ISSUE TITLE
Cannot build sample-app from repo or any other app following the guide

### ISSUE THREAD

**Issue by Dinoshauer** [auth0/react-native-lock-ios#18]
Hello!
I'm pretty new at this so excuse any obvious errors;

I'm trying to build an app with auth0 and firebase, I've followed the guide here: https://auth0.com/docs/quickstart/native-mobile/react-native-ios/firebase

But there are a number of things that are failing:

* The `Podfile` format seems to be wrong, I tried upgrading cocoapods to version `1.0.0.beta.6` to no avail
* I'm getting the error: `'LockReactNative/A0LockReactModule.h' file not found`

Using the `Podfile` from `sample-app/` in this repo installs successfully but if I paste the contents from the guide it will fail.

I'm hoping that resolving #4 will make it easier to use your service. :)

Let me know if you need any other info

**Comment by hzalaz** [comment]
@Dinoshauer I am going to change the guide a little bit to make it clear for people not familiar with iOS. I tried to use the approach described in #4 but it's more complicated than using CocoaPods because of the native dependencies, so I'll keep looking since RN won't provide a good support for that sadly.

**Comment by Dinoshauer** [comment]
Cool :) Thanks for the quick reply. Would it be recommendable to just use your api directly instead of your module?

**Comment by hzalaz** [comment]
@Dinoshauer depends on your needs. This module provides a UI for your login screen on top of what Auth0 offers, if you need a more custom UI maybe using the API directly is the way to go.
