### ISSUE TITLE
how to use both ios and android libs in the same entry file

### ISSUE THREAD

**Issue by julesbou** [auth0/react-native-lock-ios#19]
I have an application where the entry file is `index.js` (i.e. i'm not using `index.android.js` nor `index.ios.js`).

I'm a bit surprised about the choice to split your library into two projects `react-native-lock-ios` and `react-native-lock-android`, this decision seems to be more developer friendly than user friendly.

That being said, how can I import both libraries in my `index.js` file? I tried many things like:

```js
if (Platform === 'ios') {
  import Auth0Lock from 'react-native-lock-ios';
} else {
  import Auth0Lock from 'react-native-lock-android';
}
```

_(which of course doesn't work because es6 does not allows dynamic import/export.)_

**Comment by fforres** [comment]
How about you go with the old-school `require()`

**Comment by cancan101** [comment]
Why not add another js file that just does the imports and have one version of that for android and one for ios and then export `Auth0Lock` from that file.

**Comment by fforres** [comment]
You fixed it @julesbou 
Would be cool to leave your thoughts in case someone else is asking the same :)

**Comment by julesbou** [comment]
__Both of your solutions are better I guess.__

I created two entry files (one for ios, one for android) and exported `Auth0Lock` globally:

```
// index.ios.js
global.Auth0Lock = require('react-native-lock-ios');
import {} from './index.js';
```
