### ISSUE TITLE
ld: 221 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by cancan101** [auth0/react-native-lock-ios#3]
Once I have `pod install` and then `open` the `.xcworkspace`. Attempting to run:
```
duplicate symbol _OBJC_CLASS_$_RCTVirtualImageManager in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTVirtualImageManager.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTImage.a(RCTVirtualImageManager.o)
duplicate symbol _OBJC_METACLASS_$_RCTVirtualImageManager in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTVirtualImageManager.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTImage.a(RCTVirtualImageManager.o)
duplicate symbol _OBJC_CLASS_$_RCTImageStoreManager in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTImageStoreManager.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTImage.a(RCTImageStoreManager.o)
...
duplicate symbol _OBJC_METACLASS_$_RCTWebSocketExecutor in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTWebSocketExecutor.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a(RCTWebSocketExecutor.o)
duplicate symbol _OBJC_IVAR_$_RCTWebSocketExecutor._url in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTWebSocketExecutor.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a(RCTWebSocketExecutor.o)
duplicate symbol _OBJC_IVAR_$_RCTWebSocketExecutor._jsQueue in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTWebSocketExecutor.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a(RCTWebSocketExecutor.o)
duplicate symbol _OBJC_IVAR_$_RCTWebSocketExecutor._socketOpenSemaphore in:
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libReact.a(RCTWebSocketExecutor.o)
    /Users/alex/Library/Developer/Xcode/DerivedData/qsi-dbkmltjrefgyjbctqvuiubbxvspu/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a(RCTWebSocketExecutor.o)
ld: 221 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mhollweck** [comment]
+1

**Comment by hzalaz** [comment]
This is caused by having two copies of React Native in the Xcode project, one from CocoaPods and another as a subproject. Since Lock will need cocoapods to fetch it's dependencies, the suprojects should be removed, which is everything under `Libraries` inside Xcode.

**Comment by huangkaiw3n** [comment]
@hzalaz thanks, you just solved my problem with a react-native google maps ios project that was installed through CocoaPods. Was stuck on it for hours and hours as the project could build in Debug and Release but throws these errors when attempting to Archive.

**Comment by nikolakanacki** [comment]
How exactly do you fix this tho? Had the same problem with `react-native-maps`

**Comment by nikolakanacki** [comment]
Found it, nevermind. For anybody else having the same issue: Look at your `Podfile`, take a note of all the modules declared in there and remove **those exact** modules in Xcode under `Libraries`.

**Comment by richardcalahan** [comment]
@nikolakanacki When I remove these references in Libraries, the duplicate errors go away, but I get runtime errors when building. For example, removing RCTImage results in all images not being able to render (I get red boxes instead). 

Any more specifics on how to remove these dupes?

**Comment by nikolakanacki** [comment]
Just brushed through the relevant codebase where I had this problem: what I ended up doing is removing those dupes from the Podfile instead of the Xcode Libraries (effectively leaving the Libraries group untouched for this fix). Also found a "@NOTE" in the Podfile I've (apparently) left for myself saying that the first solution I posted above "wont build production". Hope this helps.

**Comment by nikolakanacki** [comment]
It also just occured to me that "production" (at the time being) may have ment "run from Xcode" vs "run from rn cmdline"

**Comment by bitsal** [comment]
@nikolakanacki
When I removed 
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTGeolocation',
    'RCTActionSheet',
    'RCTNetwork',
    'RCTWebSocket'
  ]
```
from my Podfile `0.11.0` React is installing by `pod install`

How to deal with it?

**Comment by luco** [comment]
Anyone getting this error, I manage to fix it by this answer:
https://github.com/airbnb/react-native-maps/issues/718#issuecomment-257476236

**Comment by cbartondock** [comment]
@bitsal ditto. Did you ever find a fix?

**Comment by bitsal** [comment]
I just removed React lib and their sublibs from cocoapods and linked them manually.

**Comment by cbartondock** [comment]
When I do that and run pod install it tries to install React 0.11.0 of all things

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 8of** [comment]
Try to add code at the very end of Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

**Comment by hszeto** [comment]
@8of thanks!! i've wasted days on this issue... your code seems to help !

**Comment by aterribili** [comment]
@8of thanks!! I spent a lot of time trying to fix that. <3

**Comment by ashraf-patel** [comment]
@8of Thanks dude!

**Comment by robertoclavijob** [comment]
thanks @8of
