### ISSUE TITLE
Cannot get native Facebook login to work

### ISSUE THREAD

**Issue by klatchbaldar** [auth0/react-native-lock-ios#8]
I have followed all the Quick Start guides and I can get the native iOS Auth0 to work with the native Facebook login but not with React.

**Comment by keeth** [comment]
@klatchbaldar are you trying this in iOS 9?  Starting with 9.0 the default FBSDK behavior is to log in with Safari.

https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/Internal/ServerConfiguration/FBSDKServerConfigurationManager.m#L226

**Comment by klatchbaldar** [comment]
Yes, 9.X but the flow with Facebook using the react library is different than the flow using the iOS example.  It seems like a web view that is not Safari is initiated and the FB cookies are not present so it forces the user to enter all FB credentials again (not desirable).

**Comment by keeth** [comment]
Do you have WebKit.framework under 'Linked Frameworks and Libraries'?

**Comment by klatchbaldar** [comment]
I added it but it didn't seem to make a difference.  Any other suggestions?

**Comment by klatchbaldar** [comment]
Turning on [A0LockLogger logAll] gets:

-- Authenticating with connection facebook
-- Authenticating facebook with WebView authenticator

**Comment by keeth** [comment]
set a breakpoint in A0WebViewAuthenticator.authenticateWithParameters and see which controller is returned by newWebControllerWithParameters - either A0WebKitViewController or A0WebViewController.. not sure if that's the issue but prolly good to verify if the webkit controller is being picked or not

**Comment by keeth** [comment]
I think I just figured this out... 

You need to add the integrations key when you call the Lock constructor.  This will cause the Lock-Facebook integration to be used (make sure it is part of your project), which in turn uses FBSDKLoginKit to do the auth with SafariViewController if available.

```
var lock = new Auth0Lock({
      clientId: Config.get('auth0ClientId'),
      domain: Config.get('auth0Endpoint'),
      integrations: {
        facebook: {
          permissions: ['public_profile']
        }
      }});
```

**Comment by klatchbaldar** [comment]
Amazing! Working now.  Many thanks I would have never thought that was the issue.
