### ISSUE TITLE
authParams applied inconsistently

### ISSUE THREAD

**Issue by keeth** [auth0/react-native-lock-ios#9]
If I call 

    lock.show({})

 with an empty params object, I can log in successfully.

However if I call 

    lock.show({authParams:{}})

or say

    lock.show({authParams:{connection_scopes: {facebook: ['user_posts']}}})

authenticationParametersFromOptions() will build a parameter dictionary that is missing the 'device' item, which causes login to fail.

I need to explicitly pass in scope to make it work

    lock.show({authParams:{scope: 'openid offline_access', connection_scopes: {facebook: ['user_posts']}}})

This is very confusing to a new user.

Additionally, the connection_scopes are totally ignored by A0WebViewAuthenticator - it seems that for other IDPs the params get the 'connection' property set (in registerAuthenticationProvider):

    params[A0ParameterConnection] = connectionName;

But this is not set for A0WebViewAuthenticator.  Subsequently, when A0WebKitViewController.initWithAPIClient is called, [parameters asAPIPayload] returns a parameter dictionary with connection_scopes missing, because it is trying to look up the connection scopes for the selected connection, but none is set.

I'll open a separate ticket on Lock.iOS as I believe this second issue is a bug in that project.

**Comment by hzalaz** [comment]
Will be fixed in auth0/Lock.iOS-OSX#211
